apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    targetRevision: 1.19.2
    helm:
      valuesObject:
        crds:
          enabled: true
        config:
          apiVersion: controller.config.cert-manager.io/v1alpha1
          kind: ControllerConfiguration
          enableGatewayAPI: true
        webhook:
          validatingWebhookConfiguration:
            namespaceSelector:
              matchExpressions:
                - key: control-plane
                  operator: NotIn
                  values:
                    - 'true'
                - key: kubernetes.azure.com/managedby
                  operator: NotIn
                  values:
                    - aks
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
