apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-gateway
    repoURL: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
    targetRevision: 2.3.0
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
