apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v3.2.3
- base/reference-grant.yaml

patches:
- path: patches/argocd-cmd-params-cm.yaml
