{{- $privateKeys := .Values.dotenvPrivateKeys | required ".Values.dotenvPrivateKeys is required and cannot be null or empty." -}}
{{- range $env, $key := $privateKeys -}}
apiVersion: v1
kind: Secret
metadata:
  name: dotenv-private-key-{{ $env }}
  namespace: argocd
stringData:
  key: {{ $key }}
---
{{- end -}}
