{{- $gitPassword := .Values.gitPassword | required ".Values.gitPassword is required and cannot be null or empty." -}}
{{- $gitUrl := .Values.gitUrl | required ".Values.gitUrl is required and cannot be null or empty." -}}
apiVersion: v1
kind: Secret
metadata:
  name: github-repo-credential
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/ordinal-fomojis/ProjectAlkanes-IAC
  username: admin
  password: {{ $gitPassword }}
