apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: argocd-reference-grant
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: shovel-be
  to:
  - group: ""
    kind: Service
