{{- range $config := .Values.environments -}}
{{- if $config.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $config.name }}-deployment
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $config.name }}-shovel-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $config.name }}-shovel-app
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: {{ $config.name }}-shovel-be
        image: shovelacr.azurecr.io/shovel-be:{{ $.Values.imageTag }}
        env:
        - name: APP_ENV
          value: {{ $config.name }}
        - name: NODE_ENV
          value: production
        - name: {{ include "dotenvKeyName" $config }}
          valueFrom:
            secretKeyRef:
              name: {{ include "dotenvSecretName" $config }}
              key: key
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
---
{{- end -}}
{{- end -}}
