{{- range $config := .Values.environments -}}
{{- if $config.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $config.name }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $config.name }}-deployment
  minReplicas: {{ ($config.autoscaling).minReplicas | default $.Values.autoscaling.minReplicas }}
  maxReplicas: {{ ($config.autoscaling).maxReplicas | default $.Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ ($config.autoscaling).targetCPUUtilizationPercentage | default $.Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ ($config.autoscaling).targetMemoryUtilizationPercentage | default $.Values.autoscaling.targetMemoryUtilizationPercentage }}
---
{{- end -}}
{{- end -}}
