{{- range $config := include "routes" . | fromJsonArray -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $config.name }}-http-route
spec:
  parentRefs:
  - name: gateway
    sectionName: {{ $config.name }}-https
  hostnames:
  - "{{ $config.subdomain }}.shovel.space"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ $config.service }}
      namespace: {{ $config.namespace }}
      port: {{ $config.port }}
---
{{- end -}}
